# Petición vacía
POST http://localhost:3001/api/blogs

###
# Petición solo título
POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-type: application/json

{
    "title": "Hola mundo"
}

###
# Petición solo autor
POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-type: application/json

{
    "author": "Juan Bautista"
}

###
# Petición solo url
POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-type: application/json

{
    "url": "https://github.com/bautista225",
}

###
# Petición solo likes
POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-type: application/json

{
    "likes": 33,
}

###
# Petición completa
POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzJhMDM5OWY3ZWY0MzYyMjhmMjEwYmYiLCJpYXQiOjE3MzA4MTgxOTksImV4cCI6MTczMDgyMTc5OX0.YPOgf01-TEiPQ--XwQjHni2pn43WlfHpDnc2jr7ebzY

{
    "title": "Nota realizada con token por el usuario mluukkai",
    "author": "mluukkai",
    "url": "https://github.com/bautista225",
    "likes": 33
}